### ISSUE TITLE
Components log wrong ODS shared library version 

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#148]
**Describe the bug**
When an ODS component runs, it logs the ODS shared library's version (git rev) like so:

```
Loading library ods-library@1.2.x
Attempting to resolve 1.2.x from remote references...
...
Assembled configuration: [..., odsSharedLibVersion:1.2.x, ...]
```

However, in a Release Manager context, the Release Manager pipeline itself `@Library` includes the ODS shared library itself, which effectively determines the library version for all orchestrated components. The way we currently use to determine the library version does not reflect that.

**Affected version (please complete the following information):**
 - OpenDevStack 2

**Comment by clemensutschig** [comment]
This is a jenkins feature (only the first version is loaded, and fixed in master - thru extension labels .. where we also add the mro shared lib version .. 

![image](https://user-images.githubusercontent.com/40628552/80678285-ee9c6b00-8aba-11ea-920e-0738d02dc49f.png)

coming from
https://github.com/opendevstack/ods-jenkins-shared-library/blob/0700064508b604d8627f86a8643601fdf6e91146/src/org/ods/orchestration/util/Project.groovy#L1063-L1078

I am not aware of any document we would put this in (and if so, the data is now available)
