### ISSUE TITLE
Build fails for yarn install on nodejs slave

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#275]
**Describe the bug**
Builds on the nodejs slave are failing when using `yarn install` because yarn is not configured to use a corporate proxy. Builds do not fail when using `npm install` instead.

**To Reproduce**
Run `yarn install`in an ODS components in our enterprise environment.

**Affected version (please complete the following information):**
 - OpenDevStack 2.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
+ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/iconv-lite/-/iconv-lite-0.4.13.tgz: unexpected end of file".
info If you think this is a bug, please open a bug report with the information provided in "/tmp/workspace/pltfmdev-cd/pltfmdev-cd-demo-app-front-end-master/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Additional context**
A proxy and nexus needs to be configured as described at https://www.jhipster.tech/configuring-a-corporate-proxy/.

**Comment by metmajer** [comment]
FYI @clemensutschig

**Comment by clemensutschig** [comment]
@metmajer Workaround.  Try: https://www.garysieling.com/blog/using-sonatype-nexus-yarn-npm-replacement/amp/

**Comment by clemensutschig** [comment]
@ManuelFeller can you fix this..  ? Default setup should point to nexus

**Comment by ManuelFeller** [comment]
Will check tomorrow

**Comment by ManuelFeller** [comment]
Hi. Question: do we talk about the corporate proxy or an internal registry?

Since we have no setting for a proxy in the `npmrc` we deploy I am surprised to hear that that would work - or is it just unaffected because the nexus host is already set as source and does not need to go through the proxy?

Second: are we OK to change the secrets for this slave?
I am asking because I have trouble finding any location where we could save an auth-token like the one used in the `npmrc`. Right now it seems that yarn would require to get username and password in the passed URL via `yarn config` commands. So we need to either change the secrets for this one or add redundant new ones.

I can imagine to change our current file copy method for npm to a bunch of command line calls performing the actions, so that we have a unified way for both packet managers - instead of handling npm in one way and yarn in another...

**Comment by clemensutschig** [comment]
@ManuelFeller  - see https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-slaves/nodejs10-angular/Dockerfile.rhel7#L66-L74 

here you have the auth token as well ..

regarding proxy > check https://github.com/opendevstack/ods-quickstarters/blob/master/common/jenkins-slaves/maven/set_maven_proxy.sh

**Comment by clemensutschig** [comment]
@ManuelFeller  - status?

**Comment by ManuelFeller** [comment]
After quite some reading and experimenting I found a solution. For knowledge sharing I want to describe the issue quickly:

- yarn ignores the registry setting in an .npmrc file; you need to set it in the yarn config separately (see https://github.com/yarnpkg/yarn/issues/606)
- yarn can get the other information (auth info and so on) from an .npmrc file, but therefore it has to be at an expected location with the expected name

It turned out that our current name and location (/HOMEDIR/.npm-global/etc/npmrc) in the slave is not where yarn expects it, it has to be /HOMEDIR/.npmrc

I will soon adjust the Dockerfile for the slave to have the .npmrc where it is expected as well as adding the proper .yarnrc file to make sure the nexus url is used as yarn registry

**Comment by ManuelFeller** [comment]
Having the comment from Clemens regarding what to add in the default and the possibility to just use
```
npm config set proxy http://username:password@host:port
npm config set https-proxy http://username:password@host:port
```
and 
```
yarn config set proxy http://username:password@host:port
yarn config set https-proxy http://username:password@host:port
```
in the Jenkinsfile (does not add more then a few seconds to the build process) I will close this issue now
