### ISSUE TITLE
Rename ods git ref

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-quickstarters#299]
What component `ods_git_ref` alludes to is unclear, when it only points to the git reference of the shared library. 
To make its context more obvious, I suggest renaming it to : `ods_shared_lib_branch` or `ods_shared_lib_git_ref`

**Comment by michaelsauter** [comment]
`ods_git_ref` is named after the parameter `ODS_GIT_REF` in `ods-core.env` (ods-core repo). Renaming it here would make that connection not as clear ... ?

**Comment by sino92** [comment]
I am not sure if I completely understand the connection. Is it to be consistent with `ods-core` parameter?  
In the case of ods core, it is used to pick the slave-base, webhook proxy and jenkins agent versions. Whereas in here its only related to desired jenkins shared lib to use. 
IMHO, from the perspective of a developers using only provisioning app to create projects, ods_git_ref can sound confusing.

**Comment by michaelsauter** [comment]
The parameter from ods-core is used everywhere. As an admin, you configure the Git reference of your ODS installation once, and then it is passed down to every place where this is needed. AThe `Jenkinsfile.template` gets the value from ods-core also - just via a few steps.

Note that your use case (from the ods-contrib script) is not the "normal" case. The "normal" case is quickstarter provisioning via the prov app, and the prov app passes a parameter `ODS_GIT_REF`, which the prov app itself reads from its `ConfigMap`, in which the parameter is set through the `ods-core.env` file ... that's why the parameter is called the same everywhere - because its value should normally be the same everywhere.

**Comment by sino92** [comment]
I see... They're inseparable as `ODS_GIT_REF` is passed as a Jenkins parameter all the way to `RenderJenkinsfileStage`. Maybe an extra param can be introduced in `ods-core` for this but the outcome doesn't seem to worth the effort at this point.

**Comment by michaelsauter** [comment]
Yea extra param might work, but then usually you want it to be the same param. OK with closing for now?

**Comment by sino92** [comment]
Yes the param most likely could be duplicate for most of the steps. Yup closing it.
