### ISSUE TITLE
Error with new Spring Boot Quickstarter

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-quickstarters#50]
**Describe the bug**
On first build, the build of a Spring Boot application fails with errors

**To Reproduce**
1. Provision a Project
2. Add a Spring Boot Qucikstarter
3. Trigger first build (or see automated first build)

**Expected behavior**

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 2

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
6 actionable tasks: 5 executed, 1 up-to-date
[Pipeline] junit
Recording test results
No test report files were found. Configuration error?
[Pipeline] }
[Pipeline] // withEnv
```

**Comment by michaelsauter** [comment]
I can confirm that this also happens for us, maybe related to https://github.com/opendevstack/ods-project-quickstarters/pull/441?

**Comment by tjaeschke** [comment]
@stefanlack What do you think? Im not sure if this could be related.

**Comment by stefanlack** [comment]
This is not releated to https://github.com/opendevstack/ods-project-quickstarters/pull/441, since the new spring version is also updated in the new quickstarter with commits from @kiwo : https://github.com/opendevstack/ods-quickstarters/commit/e361fc9a57b24a74ed58a4bd94560becb2812ef3 and https://github.com/opendevstack/ods-quickstarters/commit/404611f6750ae8b8c19febc86840701b1b3ab2c4

**Comment by michaelsauter** [comment]
@stefanlack I rather thought that maybe some test locations or so might have changed with JUnit4 -> JUnit 5.

**Comment by stefanlack** [comment]
PR will be created soon.
