### ISSUE TITLE
add '.pipeline-config.yml' to root of each project quickstarter

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#53]
**Is your feature request related to a problem? Please describe.**
No, MRO enhancement

**Describe the solution you'd like**
add a file called '.pipeline-config.yml' to each project quickstarter

**Describe alternatives you've considered**
none, needed.

**Additional context**
leave for now empty ...

**Comment by michaelsauter** [comment]
What should be the content of that file?

**Comment by clemensutschig** [comment]
empty ... we are still in discussions - but from a structural pov - it should be in.

**Comment by metmajer** [comment]
@clemensutschig @michaelsauter `.pipeline-config.yml` has been a name I had randomly picked in previous MRO PoCs. Since we now have a Release Manager component, it would make sense to align the naming. First of all, here's about what would go in here:

#### Contents

- the user provides metadata on the project that is required by / helpful for the release manager's orchestration or document generation parts (such as component-specific metadata)
- the user can announce dependencies on other components so the release manager can derive a dependency tree and correctly orchestrate components

#### Naming Options

1) `.release-manager-config.yml`
2) `.release-manager.yml`
3) `release-manager.yml`
4) `metadata.yml`

Looking at other open source solutions, a `-config` suffix seems superfluous. [Test Kitchen](https://kitchen.ci), for example, supports a `kitchen.yml` (or `.kitchen.yml`) for config support. I vote for 3) and consider 4) too abstract.

**Comment by michaelsauter** [comment]
Agree on 3. Should it really be empty or can we have some kind of example content in there?

**Comment by metmajer** [comment]
You could pre-populate the file with:

```
---
dependencies: []
```

This would announce to the release manager that this component has no dependencies on other components. In case `dependencies` gets removed, the release manager will be to handle this gracefully.

@clemensutschig and I may need to add further properties needed to support specific release manager functionality -- so let's keep this ticket open until we know.

**Comment by michaelsauter** [comment]
@metmajer Cool, will do.
