### ISSUE TITLE
AWS Quickstarter: Refactor Jenkinsfile contents into a dedicated shared library

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-quickstarters#631]
In the near future, we will have several AWS-related Quickstarters to make heavily sought-after Cloud services more easily consumable. Therefore, we will benefit from a refactoring of the contents of the current AWS (Plain) Quickstarter's Jenkinsfile into a dedicated shared library, for example `ods-aws-jenkins-shared-library`.

As a result, the bulk of operations would be inside this dedicated Jenkins shared library so that any specialised AWS-related Quickstarters, such as RDS, would not duplicate the entire codebase. Ideally, the Jenkinsfile in the AWS (Plain) Quickstarter is reduced to a handful of lines only.

**Comment by nichtraunzer** [comment]
Apart from reducing the amount of duplicated code we will increase stability, because we remove the possibility of interacting with standard execution context methods through the end user. We also got cleaner interfaces which reduces the amount maintenance efforts. 
The upcoming Tekton (@felipecruz91) initiative would largely benefit from a refactored Jenkins file, too. Having just method calls for test, deploy and smoke, and logic moved to a dedicated library will reduce migration efforts  to Tekton pipelines.
Unfortunately we hardly can refactor/remove the Makefile since it is an integral part of the local development process.

**Comment by nichtraunzer** [comment]
Today I met with @gerardcl and @michaelsauter. Both struggle a little bit with the situation that you requested a dedicated shared library, but apart form that they like this. 
@gerardcl offered to provide me some kickstart on that an we can do a pair programming session and do some testing in an ODS in a Box. He will also provide some more technical aspects separately.

**Comment by gerardcl** [comment]
hi! 

yes, we were discussing the approach to tackle this and we discussed among two main options first:

1- the one already proposed: having a dedicated and separated shared library for the quickstarter (or maybe more than just the AWS and maybe more infrastructure/terraform wise).

2- another proposal would be to start implementing this from a shared lib service point of view as we have already services for bitbucket, nexus, openshift, etc... hence implementing its own service integrated in the current jenkins shared lib plus its own stages using such service and the other ones existing if needed (AFAIK that is already happening in the current Jenkinsfile of the AWS QS).

After discussing we have seen that maybe as a starting point would make sense to start with the 2nd approach since:
- that will provide kind of a developer journey to the ones that will be implementing this -> getting into the way the lib thought and implemented, styles, coding structures, testing, ...
- it is kind of a small step to later see maybe different patterns also -> so if it gets really isolated and/or big then we can switch to its own library, but as said we can see other patterns first...
- from a LeVa point of view going to 2nd option would mean a transparent change/addition
- since we don't have/need separated versioning the 2nd option would perfectly fit in the ODS releasing phases approach

does it make sense to you @metmajer ? if yes, we will proceed in a first handson session and try to implement a first stage with an initial service implementation...

**Comment by metmajer** [comment]
Hey @gerardcl and @nichtraunzer. Just adding some thoughts...

- If we were designing the shared library again today, knowing that we'll not only delivery applications into OpenShift, but also Cloud, Salesforce, SAP, etc. we'd most likely come up with a set of shared libraries, e.g. a foundational and one for each target platform. Maybe this is just how I would do it :)
- Now that target runtime platforms beyond OpenShift, Quickstarters (not all but many) will be owned by the teams who own a  runtime platform, and are supported by the community if possible. Now, why should the improvement of Quickstarter, e.g. the introduction of a new Stage, depend on the release cycle of ODS? I would really like to see those things decoupled (unless the improvement affects all Quickstarters of course and therefore requires to be part of the "Core").
- What is started and owned by one team will hopefully become a community effort and we already see such requests: a team has asked if they can provide their stage implementations into the AWS Quickstarter and thereby make them a "standard", accessible by anyone. Just another reason why Quickstarters should not depend on the release of ODS.

@gerardcl I understand that you propose the second approach as a starting point and I am not saying that my approach is the best one. I am not yet fully aware of the pros and cons to be honest. If anyone know about the cons, then please add them here. 

I would like to see in a minimal example how the use of two shared libraries could work. To my understanding, we can add libraries into the execution context and call the exposed functions from the Jenkinsfile. Nice. In the Tekton future, a shared library might be used assuming it does not have hard dependencies on Jenkins. For the Quickstarter-related ones this should be minimal.

**Comment by gerardcl** [comment]
hi!

I see the points, but also by following on the thoughts on your last paragraph I then see even less need on creating another jenkins shared library if that is anyway going to be deprecated on the new ods-pipeline architecture. Or are we expecting long live-time?

The 2nd proposal targets going into the direction of less effort for implementing such requirement of new stages provided by ODS for the AWS QS, since at the end they are based on a Makefile.

Nevertheless, I totally see the value of the splitting on the 1st proposal.

**Comment by metmajer** [comment]
Well, I am not sure when exactly we can switch over to Tekton in the enterprise, and I assume that we'll have a longer timespan where both Jenkins and Tekton will be in use given there are lots of brown-field applications. So, I look at it this way:

- A Jenkins Shared library exposes entry-points in the `vars/` folder, but imports functions from a `src/` folder.
- Each Tekton task has its entry-point (a foreground process in a container) that may as well use functions from a library.

The difference, to me, lies only in how to make an entry-point accessible. A library concept does not conflict with the one or the other, and can help build a maintainable bridge between both worlds. Curious about your thoughts... @gerardcl @michaelsauter @nichtraunzer @tbugfinder @felipecruz91

**Comment by michaelsauter** [comment]
@metmajer I think you raise an interesting point regarding versioning. So far, we sidestepped this issue in ODS by releasing everything in one big blob. Going forward, I agree with you that this will not work. It would be desirable for a quickstarter to evolve separately from the rest of ODS. However, to do that change I believe we need to solve some questions first:

* Should each quickstarter then live in its own repo? I like to think of one repo = one version.
* How would we handle compatibility? Quickstarters need to be compatible with ods-core, ods-provisioning-app and ods-jenkins-shared-library. How do we deal with the complexity of juggle many version? Apart from documenting (e.g. in a table like https://docs.openshift.com/container-platform/4.8/cicd/pipelines/op-release-notes.html#compatibility-support-matrix-1-5_op-release-notes), do we have technical support in place to detect when things are incompatible?
* How do quickstarters really own what belongs to them? Right now this is not really possible. Think of a quickstarter needing its own jenkins agent image (like the AWS one) or needing its own shared lib. How is this installed? Right now, there is only one central ODS install which offers the same for everyone. Quickstarters do not have an "install procedure" themselves ... how would you make a 2nd shared lib accessible?

Because of these bigger questions I favoured first adding stuff into the existing lib, but I do see your point @metmajer, that long term, it would be better owned by a separate team and decoupled from core ODS.

**Comment by metmajer** [comment]
@michaelsauter great questions, does not make it easier. I agree with putting stuff into the existing lib to avoid duplication. Modularity can be the next topic. I'd like to work out a solution with the team by the end of the year. Quickstarter development is getting traction. Thanks!
