### ISSUE TITLE
Provide an "empty" or "vanilla" QuickStarter

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-quickstarters#716]
There are a bunch of automations/tasks that run via OpenDevStack but are not quite an application or deployment to OpenShift.

Currently every QuickStarter is geared towards running a service in OpenShift and the initial run of the Jenkins pipeline will build, deploy and run an image/container. This takes up resources that need to be cleaned or if not cleaned up will take resources away from projects that need them.

* I would like to have an "empty" or "vanilla" QuickStarter that does virtually nothing with OpenShift.

* No alternatives considered

**Comment by metmajer** [comment]
@serverhorror use-cases?

**Comment by serverhorror** [comment]
Vendor provided deployments that go to cloud providers and do not support OpenShift or containers at all

**Comment by serverhorror** [comment]
Hey,

Sure. I'm about to update the docs and since this is a really small change I was just preparing a draft.

* scripted tasks -- as in running a custom shell script that takes care of complex tasks
* snapshot/restore a database from an existing production environment to an existing staging environment (to have a verified/tested and proven method to rule out human error)
* access non-cloud / non-container resources -- think: SSH/WinRM to access or modify resources that exist for on-premise solutions

Hope that helps

**Comment by serverhorror** [comment]
The code for an absolutely mininmal template that will _not_ create any image or deploy any resources to OpenShift has been added.

Not quite sure how to run tests locally on a Windows machine. Tried to update the golden files for the tests as well.

**Comment by metmajer** [comment]
Hey, I do appreciate that you consider making a contribution. Just note that it would be good why a solution needs to be created in the first place. A solution as open as this does come with documentation overhead in a regulated environment since there is little it actual contains, it also cannot be easily supported by a support team as the final result can contain anything. Therefore, I am naturally critical. Consider as well:

> scripted tasks -- as in running a custom shell script that takes care of complex tasks

- ODS can already do that: https://github.com/opendevstack/ods-jenkins-shared-library/blob/f2470541f2e9cd8d247f5924ce0f5246b2069644/src/org/ods/orchestration/util/MROPipelineUtil.groovy#L405-L423
- Example available in the test at https://github.com/opendevstack/ods-jenkins-shared-library/blob/f2470541f2e9cd8d247f5924ce0f5246b2069644/test/groovy/org/ods/orchestration/util/MROPipelineUtilSpec.groovy#L33-L97

> snapshot/restore a database from an existing production environment to an existing staging environment (to have a verified/tested and proven method to rule out human error)

I see the purpose of this. How would this work in a CI/CD context, e.g. D->Q->P?

> access non-cloud / non-container resources -- think: SSH/WinRM to access or modify resources that exist for on-premise solutions

There is a solution for this in our enterprise context: AWX/Ansible Tower that is doing this daily. Also not sure how this fits into a CI/CD world.

@serverhorror help me understand :)

**Comment by pelacables** [comment]
hey
> > scripted tasks -- as in running a custom shell script that takes care of complex tasks
> 
> * ODS can already do that: https://github.com/opendevstack/ods-jenkins-shared-library/blob/f2470541f2e9cd8d247f5924ce0f5246b2069644/src/org/ods/orchestration/util/MROPipelineUtil.groovy#L405-L423
> * Example available in the test at https://github.com/opendevstack/ods-jenkins-shared-library/blob/f2470541f2e9cd8d247f5924ce0f5246b2069644/test/groovy/org/ods/orchestration/util/MROPipelineUtilSpec.groovy#L33-L97

Which QuickStarter are we supposed to use? any docs we can read?

The problem we have is that all QuickStarters create resources in OpenShift and they need to be cleaned up. 

so, if I get it correctly we need the release manage to be able to use this?

1. create a component, likely docker-plain  (??)
2. deploy OpenShift resources (not needed?)
3. clean up the resources
4. create a release-manager (which isn't necessarily what we need, we need to run these things outside of releases as well)
5. write the script
6. hook up the configurations
7. run the pipeline

That's why I think a plain quickstarter can help:

1. create a component
2. write the script
3. run the pipeline

Does that make sense?


> > snapshot/restore a database from an existing production environment to an existing staging environment (to have a verified/tested and proven method to rule out human error)
> 
> I see the purpose of this. How would this work in a CI/CD context, e.g. D->Q->P?

This is to go _from_ P _to_ D (or some other debugging stage).

Say you have a large or complex database migration and need to test whether it will work with the migration script. Either to verify time estimates or other dimensions. Often times people will want to test with real data.

I do not see the release manager in this use-case, neither.


> > access non-cloud / non-container resources -- think: SSH/WinRM to access or modify resources that exist for on-premise solutions
> 
> There is a solution for this in our enterprise context: our AWX/Ansible Tower service is responsible for managing on-prem resources. In the future, we will integrate with those services into ODS, but that requires some concept.

We are ware of the service but were denied access by the teams running. That leaves us with little choice but to bake our own solution while we wait for it. 

We still have a use case when building R packages and then installing them or adding them to package manager. We need to ssh to a server to do any of those 2 actions.


> From your connected PR:
> 
> > * Import VMDK images to EC2
> > * Create a database snapshot and import to RDS for debugging in a specialized environment
> 
> Both to be done by AWS Quickstarter + Blueprints.

If the requirement allows us to use things like DMS (Data Migration Service) then we intend to use the QuickStarter. This is not a release task. Providing snapshots to external collaborators or populating their database is more likely to happen here. We will need to live within the constraints of collaborators and they will need to live within ours. 

Does that help?

**Comment by metmajer** [comment]
Hi @pelacables and @serverhorror,

Certain parts of ODS, including the Release Manager, expect ODS components to run on OpenShift. Then again, this is not entirely true, since we recently introduced a new ODS component type allow the AWS Quickstarter and upcoming Azure Quickstarter to break free from this constraint. However, this ability is only available to these particular Quickstarters.

Although you and your team do not require the Release Manager for your particular use-case (I would assume though that deployment orchestration based on inter-component dependencies and parallel deployments might be interesting to anyone) we need to make sure that all parts of ODS integrate well with each other. Therefore, we can't create Quickstarters that solve your particular need, but will break the experience of many others.

I believe that we would benefit from a Quickstarter that executes a script and is able to provide credentials stored in Jenkins and/or OpenShift. Components created from this Quickstarter would then be able to practically execute anything. However, certain use-cases mentioned before are better done by the respective Quickstarters which are there for a reason.

Consider as well that ODS is an open-source delivery system for application systems. It's not a toolbox for everything, such as implementing tasks. I personally believe that a task that extracts data from a database and pushes it somewhere else is not in line with the vision of ODS and should be done somewhere else. I yet have to think about how the open Quickstarter you propose would fit into the bigger picture.

Last but not least, we're working in the same environment and I'd prefer a direct interaction to better understand needs and wants of our users. Ultimately, my intention is to build a great platform and I cannot do this if I am not rooted in direct end-user feedback. I would also like to avoid to push-back your solutions simply because we've not been aligned. Thanks much, Martin

**Comment by metmajer** [comment]
> I believe that we would benefit from a Quickstarter that executes a script and is able to relay credentials stored in Jenkins and/or OpenShift Secrets. Components created from this Quickstarter would then be able to practically execute anything. However, certain use-cases mentioned before are better done by the respective Quickstarters which are there for a reason.

@serverhorror I think the Quickstarter you started could have the purpose to replace what we had implemented into the Release Manager (see my references above). However, the Release Manager would need to be able to execute this Quickstarter correctly, and I have not come to a conclusion yet regarding SLC documentation generation, for which we'd need as well a compelling concept, e.g. TIR. @clemensutschig thoughts on the latter? @serverhorror would you like to work on this?

**Comment by serverhorror** [comment]
I just started that with @pelacables -- mainly to get him in touch with the project, so hoping for him to jump in on details...

Contacted him on a side channel and he doesn't need it any more so closing.

**Comment by metmajer** [comment]
Thanks @serverhorror, appreciate your willingness to contribute and to bring more users. I already met with @pelacables, let's continue the conversations!
