### ISSUE TITLE
Quickstarters should specify the resources for the rollout process 

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-quickstarters#797]
**Describe the bug**
Once we specify quotas in Openshift (enforce resources definition in all pods), it would make the rollour process fail 

**To Reproduce**
1. Set up quotas and resources definition in all pods
2. Rollout a Quickstarter
4. See event error

**Expected behavior**
The quickstarter should be able to rollout successfully.

**Affected version:**
 - OpenShift: 4.9.x
 - OpenDevStack 4.x

**Comment by glyk0n** [comment]
By default, pods consume unbounded node resources. However, if a project specifies default container limits, then pods consume resources up to those limits.

You can also limit resource use by specifying resource limits as part of the deployment strategy. However, if a quota has been defined for your project, one of the following two items is required:

* A [limit range](https://docs.openshift.com/container-platform/3.3/admin_guide/limits.html#admin-guide-limits) defined in the project, where the defaults from the LimitRange object apply to pods created during the deployment process.

* A resources section set with an explicit requests:

```
...
strategy:
  ...
  resources:
    limits:
      requests: 
        cpu: 100m
        memory: 128Mi
  ...
```

Otherwise, deploy pod creation will fail, citing a failure to satisfy quota.
